name: Deploy to AKS - Redis Cache

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to AKS
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Apply Kubernetes manifests
        run: |
          cd kubernetes/Manifest
          kubectl apply -f redis.yaml
